<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Model</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>
<script src="site_libs/htmlwidgets-1.2/htmlwidgets.js"></script>
<script src="site_libs/plotly-binding-4.8.0/plotly.js"></script>
<script src="site_libs/typedarray-0.1/typedarray.min.js"></script>
<link href="site_libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="site_libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="site_libs/plotly-htmlwidgets-css-1.39.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="site_libs/plotly-main-1.39.2/plotly-latest.min.js"></script>
<link href="site_libs/font-awesome-5.0.13/css/fa-svg-with-js.css" rel="stylesheet" />
<script src="site_libs/font-awesome-5.0.13/js/fontawesome-all.min.js"></script>
<script src="site_libs/font-awesome-5.0.13/js/fa-v4-shims.min.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; position: absolute; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; }
pre.numberSource a.sourceLine:empty
  { position: absolute; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: absolute; left: -5em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    background-color: #2a211c;
    color: #bdae9d;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #bdae9d;  padding-left: 4px; }
div.sourceCode
  { color: #bdae9d; background-color: #2a211c; }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ffff00; } /* Alert */
code span.an { color: #0066ff; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { } /* Attribute */
code span.bn { color: #44aa43; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #43a8ed; font-weight: bold; } /* ControlFlow */
code span.ch { color: #049b0a; } /* Char */
code span.cn { } /* Constant */
code span.co { color: #0066ff; font-weight: bold; font-style: italic; } /* Comment */
code span.do { color: #0066ff; font-style: italic; } /* Documentation */
code span.dt { text-decoration: underline; } /* DataType */
code span.dv { color: #44aa43; } /* DecVal */
code span.er { color: #ffff00; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #44aa43; } /* Float */
code span.fu { color: #ff9358; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #0066ff; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #43a8ed; font-weight: bold; } /* Keyword */
code span.op { } /* Operator */
code span.pp { font-weight: bold; } /* Preprocessor */
code span.sc { color: #049b0a; } /* SpecialChar */
code span.ss { color: #049b0a; } /* SpecialString */
code span.st { color: #049b0a; } /* String */
code span.va { } /* Variable */
code span.vs { color: #049b0a; } /* VerbatimString */
code span.wa { color: #ffff00; font-weight: bold; } /* Warning */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />

</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}

.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"><img id="logo" style="width: 40px; height: 40px; vertical-align: middle;" src="R.png" /></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Topics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Intro.html">1. Intro</a>
    </li>
    <li>
      <a href="Import.html">2. Import</a>
    </li>
    <li>
      <a href="Transform.html">3. Transform</a>
    </li>
    <li>
      <a href="Model.html">4. Model</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Recommended Courses
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="http://uc-r.github.io/data_wrangling">
        <span class="fa fa-external-link-alt"></span>
         
        UC-r
      </a>
    </li>
    <li>
      <a href="https://www.coursera.org/learn/r-programming">
        <span class="fa fa-external-link-alt"></span>
         
        Coursera
      </a>
    </li>
    <li>
      <a href="https://www.pluralsight.com/courses/r-programming-fundamentals">
        <span class="fa fa-external-link-alt"></span>
         
        Pluralsight
      </a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/MBarrows20/RIntroduction">
    <span class="fa fa-code"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/MBarrows20">
    <span class="fa fa-github"></span>
     
  </a>
</li>
<li>
  <a href="https://www.linkedin.com/in/michaelabarrows">
    <span class="fa fa-linkedin"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Model</h1>
<h4 class="date"><em>Updated: 2018-08-08</em></h4>

</div>


<div id="section" class="section level1 tabset tabset-fade">
<h1></h1>
<p>This Document will provide an overview for many different statistical analyses that can be done in R. The intricacies of each of these methods will need to be further explored but this will provide you with a starting point.</p>
<div id="linear-regression" class="section level2">
<h2>Linear Regression</h2>
<p>Linear Regression is a model fitting method which attempts to predict an value, usually numeric (i.e. brokerage) using one or more explanatory variables (i.e. day of week, distance, truck bill).</p>
<div id="basic-regression" class="section level3">
<h3>Basic Regression</h3>
<p>For our examples, we will be using the <code>mtcars</code> dataset which is built into R. This dataset is very common and has several numeric variables about vehicles. They are:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw">names</span>(mtcars)</a></code></pre></div>
<pre><code>##  [1] &quot;mpg&quot;  &quot;cyl&quot;  &quot;disp&quot; &quot;hp&quot;   &quot;drat&quot; &quot;wt&quot;   &quot;qsec&quot; &quot;vs&quot;   &quot;am&quot;   &quot;gear&quot;
## [11] &quot;carb&quot;</code></pre>
<p>if we preview the first 10 rows of data, we can get a better sense for what we are dealing with.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1"><span class="kw">head</span>(mtcars,<span class="dv">10</span>)</a></code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["mpg"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["cyl"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["disp"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["hp"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["drat"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["wt"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["qsec"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["vs"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["am"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["gear"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["carb"],"name":[11],"type":["dbl"],"align":["right"]}],"data":[{"1":"21.0","2":"6","3":"160.0","4":"110","5":"3.90","6":"2.620","7":"16.46","8":"0","9":"1","10":"4","11":"4","_rn_":"Mazda RX4"},{"1":"21.0","2":"6","3":"160.0","4":"110","5":"3.90","6":"2.875","7":"17.02","8":"0","9":"1","10":"4","11":"4","_rn_":"Mazda RX4 Wag"},{"1":"22.8","2":"4","3":"108.0","4":"93","5":"3.85","6":"2.320","7":"18.61","8":"1","9":"1","10":"4","11":"1","_rn_":"Datsun 710"},{"1":"21.4","2":"6","3":"258.0","4":"110","5":"3.08","6":"3.215","7":"19.44","8":"1","9":"0","10":"3","11":"1","_rn_":"Hornet 4 Drive"},{"1":"18.7","2":"8","3":"360.0","4":"175","5":"3.15","6":"3.440","7":"17.02","8":"0","9":"0","10":"3","11":"2","_rn_":"Hornet Sportabout"},{"1":"18.1","2":"6","3":"225.0","4":"105","5":"2.76","6":"3.460","7":"20.22","8":"1","9":"0","10":"3","11":"1","_rn_":"Valiant"},{"1":"14.3","2":"8","3":"360.0","4":"245","5":"3.21","6":"3.570","7":"15.84","8":"0","9":"0","10":"3","11":"4","_rn_":"Duster 360"},{"1":"24.4","2":"4","3":"146.7","4":"62","5":"3.69","6":"3.190","7":"20.00","8":"1","9":"0","10":"4","11":"2","_rn_":"Merc 240D"},{"1":"22.8","2":"4","3":"140.8","4":"95","5":"3.92","6":"3.150","7":"22.90","8":"1","9":"0","10":"4","11":"2","_rn_":"Merc 230"},{"1":"19.2","2":"6","3":"167.6","4":"123","5":"3.92","6":"3.440","7":"18.30","8":"1","9":"0","10":"4","11":"4","_rn_":"Merc 280"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<p>you can also learn more about this dataset by typing <code>help(mtcars)</code> into the console.</p>
<p>Now, after receiving this information, our first hypothesis might be that an increase in engine displacement (<code>disp</code>) would tend to indicate a decrease in fuel efficiency (<code>mpg</code>). To determine whether or not this hypothesis holds significant statistical value, we can perform a linear regression. We do this with the following command:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1">lmcars &lt;-<span class="st"> </span><span class="kw">summary</span>(<span class="kw">lm</span>(mpg<span class="op">~</span>disp, <span class="dt">data =</span> mtcars))</a>
<a class="sourceLine" id="cb4-2" data-line-number="2">lmcars</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ disp, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.8922 -2.2022 -0.9631  1.6272  7.2305 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 29.599855   1.229720  24.070  &lt; 2e-16 ***
## disp        -0.041215   0.004712  -8.747 9.38e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.251 on 30 degrees of freedom
## Multiple R-squared:  0.7183, Adjusted R-squared:  0.709 
## F-statistic: 76.51 on 1 and 30 DF,  p-value: 9.38e-10</code></pre>
<p>The results above tell us several things. First, the formula of the linear regression is printed again. Then, we receive basic statistics about our residuals. Residuals are basically the variance between your actual data and your predicted data. The smaller your variance, the better your model. After the residual statistics, we receive information about the coefficients. Here we are interested in several things.</p>
<ol style="list-style-type: decimal">
<li>Is <code>disp</code> a significant predictor of <code>mpg</code>?</li>
<li>What change in <code>mpg</code> is effected by a 1-unit change in <code>disp</code> (i.e. slope of our regression line)?</li>
<li>What is the y-intercept of our regression line?</li>
</ol>
<p>The answers to these questions are as follows:</p>
<ol style="list-style-type: decimal">
<li><p>We can determine displacement to be a significant predictor of <code>mpg</code> because its p-value is less than 0.05. In fact, it is 9.380326510^{-10}. We could also tell this by the three asterisks to the right of the p-value. 1+ asterisks means that the p-value is at least smaller than 0.05.</p></li>
<li><p>The slope of our regression line is the ‘Estimate’ value for <code>disp</code>. In this case, it is -0.0412151. Notice, that a negative number here indicates that as <code>disp</code> increases, <code>mpg</code> will decrease.</p></li>
<li><p>Finally, the y-intercept is the ‘Estimate’ value for the ‘(intercept)’ value. In this case it is 29.5998548.</p></li>
</ol>
<p>Now that we have answered all three of our questions. We can say with statistical confidence that <strong>yes</strong>, an increase in <code>disp</code> will tend to indicate a decrease in <code>mpg</code>. The equation for this regression relationship is <span class="math display">\[ mpg = -0.0412(disp) + 29.60 \]</span></p>
</div>
<div id="model-variable-selection" class="section level3">
<h3>Model Variable Selection</h3>
<p>While this analysis might be sufficient for quick estimation of <code>mpg</code>, we have several more variables available to us that could potentially provide a more accurate estimation. While we could add all of the variables into the equation and gain a very accurate equation, this method is not very flexible or practical at scale. Therefore, we need to select which variables are important enough to keep. This is the process of variable selection.</p>
<p>A common method for variable selection is step-wise selection. In this method you can take several paths:</p>
<ol style="list-style-type: decimal">
<li>[Simple Model] Start with one explanatory variable and add on one at a time until it no longer explains a significant amount of variation</li>
<li>[Complex Model] Start with all of the explanatory variables and remove one at a time until all variables explain a significant amount of variation</li>
<li>Do both at the same time and compare the results</li>
</ol>
<p>The key values when doing step-wise model selection are the AIC/BIC values as well as the adjusted r-square value of the model as a whole. The goal in finding a good model is to minimize the AIC/BIC value and to maximize the r-square value.</p>
<p>If we return to our <code>mtcars</code> dataset, we can use this strategy to determine a better model for estimating <code>mpg</code>.</p>
<p>As a reminder, our dataset contains several numeric variables: mpg, cyl, disp, hp, drat, wt, qsec, gear, carb and two indicator variables: vs, am. Within the numeric values, <code>cyl</code>, <code>gear</code>, and <code>carb</code> are discrete variables and will be ignored. For now, we will just try to use the continuous numeric values to predict <code>mpg</code> for ease of interpretation. Additionally, since <code>qsec</code> is not really a characteristic of the car but rather a performance metric, we will leave it out of our analysis as well.</p>
<p>Our first attempt will be to fit the model in a backwards fashion. This will generally maintain a maximum accuracy at the cost of increased complexity. As you can see below, the step function evaluates a model object (<code>model1</code>). It tests the full model first and then removes variables that don’t significantly explain a change in <code>mpg</code> until it ends up at the “best” model.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1">model1 &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg<span class="op">~</span>disp<span class="op">+</span>hp<span class="op">+</span>drat<span class="op">+</span>wt, <span class="dt">data =</span> mtcars)</a>
<a class="sourceLine" id="cb6-2" data-line-number="2"><span class="kw">step</span>(model1, <span class="dt">direction =</span> <span class="st">&#39;backward&#39;</span>)</a></code></pre></div>
<pre><code>## Start:  AIC=65.77
## mpg ~ disp + hp + drat + wt
## 
##        Df Sum of Sq    RSS    AIC
## - disp  1     0.844 183.68 63.919
## &lt;none&gt;              182.84 65.772
## - drat  1    12.153 194.99 65.831
## - hp    1    60.916 243.75 72.974
## - wt    1    70.508 253.35 74.209
## 
## Step:  AIC=63.92
## mpg ~ hp + drat + wt
## 
##        Df Sum of Sq    RSS    AIC
## - drat  1    11.366 195.05 63.840
## &lt;none&gt;              183.68 63.919
## - hp    1    85.559 269.24 74.156
## - wt    1   107.771 291.45 76.693
## 
## Step:  AIC=63.84
## mpg ~ hp + wt
## 
##        Df Sum of Sq    RSS    AIC
## &lt;none&gt;              195.05 63.840
## - hp    1    83.274 278.32 73.217
## - wt    1   252.627 447.67 88.427</code></pre>
<pre><code>## 
## Call:
## lm(formula = mpg ~ hp + wt, data = mtcars)
## 
## Coefficients:
## (Intercept)           hp           wt  
##    37.22727     -0.03177     -3.87783</code></pre>
<p>In this case, the best model is determined to be <code>mpg ~ hp + wt</code> this means that even though we found <code>disp</code> to be a significant predictor of <code>mpg</code> in our simple regression equation, the combination of <code>hp</code> and <code>wt</code> actually offers “better” predictive power.</p>
<p>In order to run the model <em>foreward</em> we need to do a few extra steps. The first is to reduce the dataset to only the 5 variables we will need. The next step is to build a null model (model with no predictor variables) and a full model (the starting model of our previous method). These are what define the scope of our forward step-wise regression.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1">mtcarsSlim &lt;-<span class="st"> </span>mtcars[,<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span><span class="op">:</span><span class="dv">6</span>)]</a>
<a class="sourceLine" id="cb9-2" data-line-number="2">model2_null &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg<span class="op">~</span><span class="dv">1</span>,<span class="dt">data =</span> mtcarsSlim)</a>
<a class="sourceLine" id="cb9-3" data-line-number="3">model2_full &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg<span class="op">~</span>., <span class="dt">data =</span> mtcarsSlim)</a>
<a class="sourceLine" id="cb9-4" data-line-number="4"><span class="kw">step</span>(model2_null, <span class="dt">scope =</span> <span class="kw">list</span>(<span class="dt">lower =</span> model2_null,<span class="dt">upper =</span> model2_full), <span class="dt">direction =</span> <span class="st">&#39;forward&#39;</span>)</a></code></pre></div>
<pre><code>## Start:  AIC=115.94
## mpg ~ 1
## 
##        Df Sum of Sq     RSS     AIC
## + wt    1    847.73  278.32  73.217
## + disp  1    808.89  317.16  77.397
## + hp    1    678.37  447.67  88.427
## + drat  1    522.48  603.57  97.988
## &lt;none&gt;              1126.05 115.943
## 
## Step:  AIC=73.22
## mpg ~ wt
## 
##        Df Sum of Sq    RSS    AIC
## + hp    1    83.274 195.05 63.840
## + disp  1    31.639 246.68 71.356
## &lt;none&gt;              278.32 73.217
## + drat  1     9.081 269.24 74.156
## 
## Step:  AIC=63.84
## mpg ~ wt + hp
## 
##        Df Sum of Sq    RSS    AIC
## &lt;none&gt;              195.05 63.840
## + drat  1   11.3659 183.68 63.919
## + disp  1    0.0571 194.99 65.831</code></pre>
<pre><code>## 
## Call:
## lm(formula = mpg ~ wt + hp, data = mtcarsSlim)
## 
## Coefficients:
## (Intercept)           wt           hp  
##    37.22727     -3.87783     -0.03177</code></pre>
<p>From the output above you notice that the model starts with just the intercept. Then, it adds <code>wt</code>, then <code>hp</code> to arrive at the final model which happens to be the same as our first method. While the results are not <em>always</em> the same, it is common.</p>
<p>Finally, we will run the step-wise linear regression from both ends for good measure. This will essentially run both of these previous tests simultaneously and return the “best” model. Since both forward and backward selection returned the same model, we can expect this final method to be the same.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" data-line-number="1"><span class="kw">step</span>(model1, <span class="dt">direction =</span> <span class="st">&#39;both&#39;</span>)</a></code></pre></div>
<pre><code>## Start:  AIC=65.77
## mpg ~ disp + hp + drat + wt
## 
##        Df Sum of Sq    RSS    AIC
## - disp  1     0.844 183.68 63.919
## &lt;none&gt;              182.84 65.772
## - drat  1    12.153 194.99 65.831
## - hp    1    60.916 243.75 72.974
## - wt    1    70.508 253.35 74.209
## 
## Step:  AIC=63.92
## mpg ~ hp + drat + wt
## 
##        Df Sum of Sq    RSS    AIC
## - drat  1    11.366 195.05 63.840
## &lt;none&gt;              183.68 63.919
## + disp  1     0.844 182.84 65.772
## - hp    1    85.559 269.24 74.156
## - wt    1   107.771 291.45 76.693
## 
## Step:  AIC=63.84
## mpg ~ hp + wt
## 
##        Df Sum of Sq    RSS    AIC
## &lt;none&gt;              195.05 63.840
## + drat  1    11.366 183.68 63.919
## + disp  1     0.057 194.99 65.831
## - hp    1    83.274 278.32 73.217
## - wt    1   252.627 447.67 88.427</code></pre>
<pre><code>## 
## Call:
## lm(formula = mpg ~ hp + wt, data = mtcars)
## 
## Coefficients:
## (Intercept)           hp           wt  
##    37.22727     -0.03177     -3.87783</code></pre>
<p>As we predicted, the final model <em><strong>is</strong></em> the same as before. Knowing this, we can run a simple linear regression again to compare our values from earlier:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1">(lm1 &lt;-<span class="st"> </span><span class="kw">summary</span>(<span class="kw">lm</span>(mpg<span class="op">~</span>disp, <span class="dt">data =</span> mtcars)))</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ disp, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.8922 -2.2022 -0.9631  1.6272  7.2305 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 29.599855   1.229720  24.070  &lt; 2e-16 ***
## disp        -0.041215   0.004712  -8.747 9.38e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.251 on 30 degrees of freedom
## Multiple R-squared:  0.7183, Adjusted R-squared:  0.709 
## F-statistic: 76.51 on 1 and 30 DF,  p-value: 9.38e-10</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1">(lm2 &lt;-<span class="st"> </span><span class="kw">summary</span>(<span class="kw">lm</span>(mpg<span class="op">~</span>hp<span class="op">+</span>wt, <span class="dt">data=</span>mtcars)))</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ hp + wt, data = mtcars)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -3.941 -1.600 -0.182  1.050  5.854 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 37.22727    1.59879  23.285  &lt; 2e-16 ***
## hp          -0.03177    0.00903  -3.519  0.00145 ** 
## wt          -3.87783    0.63273  -6.129 1.12e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.593 on 29 degrees of freedom
## Multiple R-squared:  0.8268, Adjusted R-squared:  0.8148 
## F-statistic: 69.21 on 2 and 29 DF,  p-value: 9.109e-12</code></pre>
<p>You can see that while all variables in each of our models are significant (p-value &lt; 0.05) and the overall models are significant (p-value &lt;0.05), the second model actually explains about 10% more variation in <code>mpg</code>. We can tell this because the Adjusted R-squared values are 0.718 and 0.827 for the first and second model respectively.</p>
<p>With a good understanding of our models from a numeric standpoint, let’s review a few key figures. First, lets take a look at the first model with the regression equation plotted. We can do this with plotting functions built into R as such:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1"><span class="kw">plot</span>(mpg<span class="op">~</span>disp, <span class="dt">data =</span> mtcars)</a>
<a class="sourceLine" id="cb19-2" data-line-number="2"><span class="kw">abline</span>(lm1)</a></code></pre></div>
<pre><code>## Warning in abline(lm1): only using the first two of 8 regression
## coefficients</code></pre>
<p><img src="Model_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>However, many users of R agree that the <code>ggplot2</code> package offers many desirable plotting functions and therefore is used quite frequently. if we want to build the same figure in <code>ggplot2</code> syntax, we do the following:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1"><span class="kw">library</span>(ggplot2)</a>
<a class="sourceLine" id="cb21-2" data-line-number="2"><span class="kw">ggplot</span>(mtcars, <span class="kw">aes</span>(disp,mpg)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb21-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb21-4" data-line-number="4"><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&#39;lm&#39;</span>, <span class="dt">se =</span> F)</a></code></pre></div>
<p><img src="Model_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>You will notice that using <code>ggplot2</code> prevents you from having to build a linear model first. Instead, you can just use the geom_smooth() option. <code>ggplot2</code> can be confusing at first but there are several good resources out there, including <a href="https://ggplot2.tidyverse.org/reference/">their own documentation</a>.</p>
<p>The fundamental difference between the built-in plotting functions and <code>ggplot2</code> is that the base R function builds layered images and ggplot2 builds one cohesive image file. This makes the base functions arguably more flexible because each layer doesn’t care about what’s in the other layers. However, it also means that there is potential for unintentional plotting of incorrect information. I encourage you to try both and experience where each method excels.</p>
<p>Now, since the second model uses two explanatory variables, we have some options for how we want to display the information. The first option is to plot the first variable (hp) as normal and then code the second variable (wt) as something else (i.e. color, size, shape, etc). To demonstrate, let’s code it as color where darker colors indicate a heavier car.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" data-line-number="1"><span class="kw">ggplot</span>(mtcars, <span class="kw">aes</span>(hp,mpg, <span class="dt">color =</span> wt)) <span class="op">+</span></a>
<a class="sourceLine" id="cb22-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_point</span>()</a></code></pre></div>
<p><img src="Model_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>The next option is to plot the values in three dimensional space. For this we will need another package called <code>plotly</code></p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1"><span class="kw">require</span>(plotly)</a></code></pre></div>
<pre><code>## Loading required package: plotly</code></pre>
<pre><code>## 
## Attaching package: &#39;plotly&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:ggplot2&#39;:
## 
##     last_plot</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     filter</code></pre>
<pre><code>## The following object is masked from &#39;package:graphics&#39;:
## 
##     layout</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" data-line-number="1"><span class="kw">plot_ly</span>(mtcars, <span class="dt">x=</span> <span class="op">~</span>wt, <span class="dt">y =</span> <span class="op">~</span>hp, <span class="dt">z =</span> <span class="op">~</span>mpg) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb29-2" data-line-number="2"><span class="st">  </span><span class="kw">add_markers</span>()</a></code></pre></div>
<div id="htmlwidget-d1ee6738aa64ed37bc8e" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-d1ee6738aa64ed37bc8e">{"x":{"visdat":{"11c4684b2023":["function () ","plotlyVisDat"]},"cur_data":"11c4684b2023","attrs":{"11c4684b2023":{"x":{},"y":{},"z":{},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter3d","mode":"markers","inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"scene":{"xaxis":{"title":"wt"},"yaxis":{"title":"hp"},"zaxis":{"title":"mpg"}},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":[{"name":"Collaborate","icon":{"width":1000,"ascent":500,"descent":-50,"path":"M487 375c7-10 9-23 5-36l-79-259c-3-12-11-23-22-31-11-8-22-12-35-12l-263 0c-15 0-29 5-43 15-13 10-23 23-28 37-5 13-5 25-1 37 0 0 0 3 1 7 1 5 1 8 1 11 0 2 0 4-1 6 0 3-1 5-1 6 1 2 2 4 3 6 1 2 2 4 4 6 2 3 4 5 5 7 5 7 9 16 13 26 4 10 7 19 9 26 0 2 0 5 0 9-1 4-1 6 0 8 0 2 2 5 4 8 3 3 5 5 5 7 4 6 8 15 12 26 4 11 7 19 7 26 1 1 0 4 0 9-1 4-1 7 0 8 1 2 3 5 6 8 4 4 6 6 6 7 4 5 8 13 13 24 4 11 7 20 7 28 1 1 0 4 0 7-1 3-1 6-1 7 0 2 1 4 3 6 1 1 3 4 5 6 2 3 3 5 5 6 1 2 3 5 4 9 2 3 3 7 5 10 1 3 2 6 4 10 2 4 4 7 6 9 2 3 4 5 7 7 3 2 7 3 11 3 3 0 8 0 13-1l0-1c7 2 12 2 14 2l218 0c14 0 25-5 32-16 8-10 10-23 6-37l-79-259c-7-22-13-37-20-43-7-7-19-10-37-10l-248 0c-5 0-9-2-11-5-2-3-2-7 0-12 4-13 18-20 41-20l264 0c5 0 10 2 16 5 5 3 8 6 10 11l85 282c2 5 2 10 2 17 7-3 13-7 17-13z m-304 0c-1-3-1-5 0-7 1-1 3-2 6-2l174 0c2 0 4 1 7 2 2 2 4 4 5 7l6 18c0 3 0 5-1 7-1 1-3 2-6 2l-173 0c-3 0-5-1-8-2-2-2-4-4-4-7z m-24-73c-1-3-1-5 0-7 2-2 3-2 6-2l174 0c2 0 5 0 7 2 3 2 4 4 5 7l6 18c1 2 0 5-1 6-1 2-3 3-5 3l-174 0c-3 0-5-1-7-3-3-1-4-4-5-6z"},"click":"function(gd) { \n        // is this being viewed in RStudio?\n        if (location.search == '?viewer_pane=1') {\n          alert('To learn about plotly for collaboration, visit:\\n https://cpsievert.github.io/plotly_book/plot-ly-for-collaboration.html');\n        } else {\n          window.open('https://cpsievert.github.io/plotly_book/plot-ly-for-collaboration.html', '_blank');\n        }\n      }"}],"cloud":false},"data":[{"x":[2.62,2.875,2.32,3.215,3.44,3.46,3.57,3.19,3.15,3.44,3.44,4.07,3.73,3.78,5.25,5.424,5.345,2.2,1.615,1.835,2.465,3.52,3.435,3.84,3.845,1.935,2.14,1.513,3.17,2.77,3.57,2.78],"y":[110,110,93,110,175,105,245,62,95,123,123,180,180,180,205,215,230,66,52,65,97,150,150,245,175,66,91,113,264,175,335,109],"z":[21,21,22.8,21.4,18.7,18.1,14.3,24.4,22.8,19.2,17.8,16.4,17.3,15.2,10.4,10.4,14.7,32.4,30.4,33.9,21.5,15.5,15.2,13.3,19.2,27.3,26,30.4,15.8,19.7,15,21.4],"type":"scatter3d","mode":"markers","marker":{"color":"rgba(31,119,180,1)","line":{"color":"rgba(31,119,180,1)"}},"error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"line":{"color":"rgba(31,119,180,1)"},"frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"base_url":"https://plot.ly"},"evals":["config.modeBarButtonsToAdd.0.click"],"jsHooks":[]}</script>
</div>
</div>
<div id="anova" class="section level2">
<h2>ANOVA</h2>
</div>
<div id="clustering" class="section level2">
<h2>Clustering</h2>
</div>
</div>

<div class = "footer">
  <p> Created by Michael Barrows </p>
</div>



</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
